export const APPLICATION_STATUSES = Object.freeze({
  APPLIED: 'APPLIED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  SHORTLISTED: 'SHORTLISTED',
  INTERVIEW_SCHEDULED: 'INTERVIEW_SCHEDULED',
  REJECTED: 'REJECTED',
  ACCEPTED: 'ACCEPTED',
});

export const VALID_STATUSES = Object.freeze(Object.values(APPLICATION_STATUSES));

export const ROLES = Object.freeze({
  LEARNER: 'LEARNER',
  RECRUITER: 'RECRUITER',
  ADMIN: 'ADMIN',
});
